# Generated by Django 2.2 on 2020-09-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200905_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_order',
            field=models.BooleanField(default=True, verbose_name='В наличий'),
        ),
    ]
